#   This file should contain all the record creation needed to seed the database with its default values.
#   The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).

#   Examples:

#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!([{username:"Arie",email:"Arie@gmail.com",password:"27259"},
{username:"Reuven",email:"Reuven@gmail.com",password:"68411"},
{username:"Lexie",email:"Lexie@gmail.com",password:"66945"},
{username:"Maribel",email:"Maribel@gmail.com",password:"11691"},
{username:"Edik",email:"Edik@gmail.com",password:"32471"},
{username:"Gerianna",email:"Gerianna@gmail.com",password:"1142"},
{username:"Gabi",email:"Gabi@gmail.com",password:"6148"},
{username:"Rance",email:"Rance@gmail.com",password:"36246"},
{username:"Hildagarde",email:"Hildagarde@gmail.com",password:"11569"},
{username:"Cirillo",email:"Cirillo@gmail.com",password:"53964"}])

Article.create!(
    [{title:"Monkey, bleeding heart",description:"Theropithecus gelada is animal",user_id:7},
{title:"White-headed vulture",description:"Aegypius occipitalis is animal",user_id:9},
{title:"Common wallaroo",description:"Macropus robustus is animal",user_id:5},
{title:"Ring-tailed lemur",description:"Lemur catta is animal",user_id:1},
{title:"Zorilla",description:"Ictonyx striatus is animal",user_id:6},
{title:"Reedbuck, bohor",description:"Redunca redunca is animal",user_id:2},
{title:"North American porcupine",description:"Erethizon dorsatum is animal",user_id:1},
{title:"Vicuna",description:"Vicugna vicugna is animal",user_id:5},
{title:"Short-beaked echidna",description:"Tachyglossus aculeatus is animal",user_id:1},
{title:"Steenbuck",description:"Raphicerus campestris is animal",user_id:2},
{title:"Bear, grizzly",description:"Ursus arctos is animal",user_id:5},
{title:"Parrot, hawk-headed",description:"Deroptyus accipitrinus is animal",user_id:9},
{title:"Rat, desert kangaroo",description:"Dipodomys deserti is animal",user_id:1},
{title:"Gerenuk",description:"Litrocranius walleri is animal",user_id:5},
{title:"Kangaroo, jungle",description:"Macropus agilis is animal",user_id:9},
{title:"Roe deer",description:"Capreolus capreolus is animal",user_id:5},
{title:"Bear, polar",description:"Ursus maritimus is animal",user_id:7},
{title:"White-throated kingfisher",description:"Halcyon smyrnesis is animal",user_id:4},
{title:"Galapagos penguin",description:"Spheniscus mendiculus is animal",user_id:8},
{title:"Otter, african clawless",description:"Aonyx capensis is animal",user_id:7},
{title:"Tern, royal",description:"Thalasseus maximus is animal",user_id:5},
{title:"Brown brocket",description:"Mazama gouazoubira is animal",user_id:2},
{title:"Owl, australian masked",description:"Tyto novaehollandiae is animal",user_id:3},
{title:"Common green iguana",description:"Iguana iguana is animal",user_id:6},
{title:"Bushbuck",description:"Tragelaphus scriptus is animal",user_id:2},
{title:"White-necked raven",description:"Corvus albicollis is animal",user_id:1},
{title:"Asian openbill",description:"Anastomus oscitans is animal",user_id:6},
{title:"Whip-tailed wallaby",description:"Macropus parryi is animal",user_id:6},
{title:"Silver-backed fox",description:"Vulpes chama is animal",user_id:5},
{title:"Russian dragonfly",description:"Libellula quadrimaculata is animal",user_id:6},
{title:"Northern elephant seal",description:"Mirounga angustirostris is animal",user_id:9},
{title:"Bandicoot, long-nosed",description:"Perameles nasuta is animal",user_id:6},
{title:"Snake, green vine",description:"Oxybelis fulgidus is animal",user_id:1},
{title:"Leadbeateri's ground hornbill",description:"Bucorvus leadbeateri is animal",user_id:8},
{title:"Yellow-billed hornbill",description:"Tockus flavirostris is animal",user_id:7},
{title:"Stork, openbill",description:"Anastomus oscitans is animal",user_id:7},
{title:"Dove, white-winged",description:"Zenaida asiatica is animal",user_id:1},
{title:"Baboon, yellow",description:"Papio cynocephalus is animal",user_id:1},
{title:"Boar, wild",description:"Sus scrofa is animal",user_id:1},
{title:"Springbuck",description:"Antidorcas marsupialis is animal",user_id:1},
{title:"Saddle-billed stork",description:"Ephipplorhynchus senegalensis is animal",user_id:9},
{title:"Galapagos sea lion",description:"Zalophus californicus is animal",user_id:8},
{title:"Cobra, egyptian",description:"Naja haje is animal",user_id:7},
{title:"Fox, grey",description:"Vulpes cinereoargenteus is animal",user_id:2},
{title:"Laughing kookaburra",description:"Dacelo novaeguineae is animal",user_id:7},
{title:"Vulture, egyptian",description:"Neophron percnopterus is animal",user_id:8},
{title:"Southern white-crowned shrike",description:"Eurocephalus anguitimens is animal",user_id:2},
{title:"Python (unidentified)",description:"unavailable is animal",user_id:6},
{title:"Iguana, marine",description:"Amblyrhynchus cristatus is animal",user_id:4},
{title:"Vulture, griffon",description:"Gyps fulvus is animal",user_id:1},
{title:"Tammar wallaby",description:"Macropus eugenii is animal",user_id:7},
{title:"Beaver, american",description:"Castor canadensis is animal",user_id:8},
{title:"Short-beaked echidna",description:"Tachyglossus aculeatus is animal",user_id:7},
{title:"Hottentot teal",description:"Anas punctata is animal",user_id:5},
{title:"Sugar glider",description:"Petaurus breviceps is animal",user_id:2},
{title:"Sloth bear",description:"Melursus ursinus is animal",user_id:9},
{title:"Galapagos tortoise",description:"Geochelone elephantopus is animal",user_id:4},
{title:"Gazelle, grant's",description:"Gazella granti is animal",user_id:7},
{title:"Wattled crane",description:"Bugeranus caruncalatus is animal",user_id:9},
{title:"Yellow-billed stork",description:"Mycteria ibis is animal",user_id:6},
{title:"Snake, eastern indigo",description:"Drymarchon corias couperi is animal",user_id:1},
{title:"Pied crow",description:"Corvus albus is animal",user_id:4},
{title:"Otter, north american river",description:"Lutra canadensis is animal",user_id:9},
{title:"Anaconda (unidentified)",description:"Eunectes sp. is animal",user_id:4},
{title:"Great egret",description:"Casmerodius albus is animal",user_id:2},
{title:"Sheep, stone",description:"Ovis dalli stonei is animal",user_id:7},
{title:"Denham's bustard",description:"Neotis denhami is animal",user_id:9},
{title:"Waterbuck, common",description:"Kobus defassa is animal",user_id:1},
{title:"Constrictor, eastern boa",description:"Acrantophis madagascariensis is animal",user_id:1},
{title:"Long-billed cockatoo",description:"Cacatua tenuirostris is animal",user_id:3},
{title:"Bee-eater, carmine",description:"Merops nubicus is animal",user_id:5},
{title:"Colobus, white-mantled",description:"Colobus guerza is animal",user_id:5},
{title:"Black-necked stork",description:"Ephippiorhynchus mycteria is animal",user_id:1},
{title:"Blue catfish",description:"Ictalurus furcatus is animal",user_id:7},
{title:"Cormorant, flightless",description:"Nannopterum harrisi is animal",user_id:7},
{title:"Mountain lion",description:"Felis concolor is animal",user_id:3},
{title:"Rhea, greater",description:"Rhea americana is animal",user_id:9},
{title:"Three-banded plover",description:"Charadrius tricollaris is animal",user_id:7},
{title:"Mouflon",description:"Ovis musimon is animal",user_id:2},
{title:"Spotted deer",description:"Axis axis is animal",user_id:1},
{title:"Pine squirrel",description:"Tamiasciurus hudsonicus is animal",user_id:9},
{title:"Lizard, desert spiny",description:"Sceloporus magister is animal",user_id:1},
{title:"Chickadee, black-capped",description:"Parus atricapillus is animal",user_id:5},
{title:"Steller sea lion",description:"Eumetopias jubatus is animal",user_id:3},
{title:"Waxbill, black-cheeked",description:"Estrilda erythronotos is animal",user_id:2},
{title:"Ferret, black-footed",description:"Mustela nigripes is animal",user_id:8},
{title:"Jungle cat",description:"Felis chaus is animal",user_id:6},
{title:"Red-legged pademelon",description:"Thylogale stigmatica is animal",user_id:7},
{title:"Red-cheeked cordon bleu",description:"Uraeginthus bengalus is animal",user_id:1},
{title:"Pied avocet",description:"Recurvirostra avosetta is animal",user_id:4},
{title:"White-fronted bee-eater",description:"Merops bullockoides is animal",user_id:2},
{title:"Cape raven",description:"Corvus albicollis is animal",user_id:7},
{title:"Hornbill, yellow-billed",description:"Tockus flavirostris is animal",user_id:6},
{title:"White spoonbill",description:"Platalea leucordia is animal",user_id:7},
{title:"Jackrabbit, white-tailed",description:"Lepus townsendii is animal",user_id:8},
{title:"Frilled dragon",description:"Chlamydosaurus kingii is animal",user_id:5},
{title:"Monitor lizard (unidentified)",description:"Varanus sp. is animal",user_id:9},
{title:"Steenbuck",description:"Raphicerus campestris is animal",user_id:7},
{title:"Eagle, bateleur",description:"Terathopius ecaudatus is animal",user_id:3},
{title:"Red meerkat",description:"Cynictis penicillata is animal",user_id:9},
{title:"Sacred ibis",description:"Threskionis aethiopicus is animal",user_id:1},
{title:"Pied avocet",description:"Recurvirostra avosetta is animal",user_id:7},
{title:"Mockingbird, galapagos",description:"Nesomimus trifasciatus is animal",user_id:2},
{title:"Crown of thorns starfish",description:"Acanthaster planci is animal",user_id:3},
{title:"Red-cheeked cordon bleu",description:"Uraeginthus bengalus is animal",user_id:2},
{title:"Black-capped chickadee",description:"Parus atricapillus is animal",user_id:7},
{title:"Black-collared barbet",description:"Lybius torquatus is animal",user_id:7},
{title:"Chameleon (unidentified)",description:"Chamaelo sp. is animal",user_id:3},
{title:"Seal, southern elephant",description:"Mirounga leonina is animal",user_id:5},
{title:"Collared peccary",description:"Tayassu tajacu is animal",user_id:8},
{title:"Southern lapwing",description:"Vanellus chilensis is animal",user_id:3},
{title:"Siskin, yellow-rumped",description:"Carduelis uropygialis is animal",user_id:8},
{title:"Rhea, greater",description:"Rhea americana is animal",user_id:2},
{title:"Pallas's fish eagle",description:"Haliaeetus leucoryphus is animal",user_id:7},
{title:"Euro wallaby",description:"Macropus robustus is animal",user_id:2},
{title:"Albatross, waved",description:"Diomedea irrorata is animal",user_id:7},
{title:"Barking gecko",description:"Phylurus milli is animal",user_id:7},
{title:"Nighthawk, common",description:"Chordeiles minor is animal",user_id:1},
{title:"Blue crane",description:"Anthropoides paradisea is animal",user_id:1},
{title:"Llama",description:"Lama glama is animal",user_id:4},
{title:"Owl, white-browed",description:"Ninox superciliaris is animal",user_id:1},
{title:"Flamingo, chilean",description:"Phoenicopterus chilensis is animal",user_id:3},
{title:"Sheep, red",description:"Ovis ammon is animal",user_id:1},
{title:"Kangaroo, eastern grey",description:"Macropus giganteus is animal",user_id:1},
{title:"Capuchin, black-capped",description:"Cebus apella is animal",user_id:1},
{title:"Pied kingfisher",description:"Ceryle rudis is animal",user_id:3},
{title:"Boubou, southern",description:"Laniarius ferrugineus is animal",user_id:8},
{title:"African wild cat",description:"Felis silvestris lybica is animal",user_id:3},
{title:"Blue fox",description:"Alopex lagopus is animal",user_id:2},
{title:"Dog, black-tailed prairie",description:"Cynomys ludovicianus is animal",user_id:6},
{title:"Deer, red",description:"Cervus elaphus is animal",user_id:4},
{title:"Eagle, bald",description:"Haliaeetus leucocephalus is animal",user_id:5},
{title:"Albatross, galapagos 1",description:"Diomedea irrorata is animal",user_id:5},
{title:"Paradoxure",description:"Paradoxurus hermaphroditus is animal",user_id:3},
{title:"Lapwing (unidentified)",description:"Vanellus sp. is animal",user_id:5},
{title:"Bush dog",description:"Speothos vanaticus is animal",user_id:2},
{title:"Flycatcher, tyrant",description:"Myiarchus tuberculifer is animal",user_id:5},
{title:"Black rhinoceros",description:"Diceros bicornis is animal",user_id:5},
{title:"Jackal, black-backed",description:"Canis mesomelas is animal",user_id:7},
{title:"Bat, little brown",description:"Myotis lucifugus is animal",user_id:6},
{title:"Jacana, african",description:"Actophilornis africanus is animal",user_id:1},
{title:"Crane, black-crowned",description:"Balearica pavonina is animal",user_id:9},
{title:"Loris, slender",description:"Loris tardigratus is animal",user_id:6},
{title:"Lion, asian",description:"Panthera leo persica is animal",user_id:2},
{title:"Sheathbill, snowy",description:"Chionis alba is animal",user_id:8},
{title:"Flycatcher, tyrant",description:"Myiarchus tuberculifer is animal",user_id:2},
{title:"Harbor seal",description:"Phoca vitulina is animal",user_id:1},
{title:"Pied kingfisher",description:"Ceryle rudis is animal",user_id:3},
{title:"Teal, hottentot",description:"Anas punctata is animal",user_id:4},
{title:"Turkey, australian brush",description:"Alectura lathami is animal",user_id:6},
{title:"Glider, squirrel",description:"Petaurus norfolcensis is animal",user_id:8},
{title:"Galapagos mockingbird",description:"Nesomimus trifasciatus is animal",user_id:8},
{title:"Cormorant, large",description:"Phalacrocorax carbo is animal",user_id:6},
{title:"Bee-eater, nubian",description:"Merops nubicus is animal",user_id:1},
{title:"Gerbil (unidentified)",description:"Gerbillus sp. is animal",user_id:1},
{title:"Hornbill, leadbeateri's ground",description:"Bucorvus leadbeateri is animal",user_id:1},
{title:"Armadillo, nine-banded",description:"Dasypus novemcinctus is animal",user_id:5},
{title:"Cormorant, large",description:"Phalacrocorax carbo is animal",user_id:4},
{title:"South African hedgehog",description:"Erinaceus frontalis is animal",user_id:5},
{title:"Cat, kaffir",description:"Felis silvestris lybica is animal",user_id:2},
{title:"Deer, spotted",description:"Axis axis is animal",user_id:5},
{title:"Little grebe",description:"Tachybaptus ruficollis is animal",user_id:2},
{title:"Red-breasted nuthatch",description:"Sitta canadensis is animal",user_id:1},
{title:"Vulture, black",description:"Aegypius tracheliotus is animal",user_id:5},
{title:"Columbian rainbow boa",description:"Epicrates cenchria maurus is animal",user_id:6},
{title:"Lark, horned",description:"Eremophila alpestris is animal",user_id:8},
{title:"Waved albatross",description:"Diomedea irrorata is animal",user_id:4},
{title:"White-necked stork",description:"Ciconia episcopus is animal",user_id:2},
{title:"Gull, dusky",description:"Larus fuliginosus is animal",user_id:5},
{title:"Cobra, cape",description:"Naja nivea is animal",user_id:8},
{title:"Defassa waterbuck",description:"Kobus defassa is animal",user_id:3},
{title:"Duiker, gray",description:"Sylvicapra grimma is animal",user_id:4},
{title:"Red-billed toucan",description:"Ramphastos tucanus is animal",user_id:7},
{title:"Spurfowl, yellow-necked",description:"Francolinus leucoscepus is animal",user_id:5},
{title:"Robin, white-throated",description:"Irania gutteralis is animal",user_id:4},
{title:"Ibis, puna",description:"Plegadis ridgwayi is animal",user_id:1},
{title:"Turtle, long-necked",description:"Chelodina longicollis is animal",user_id:5},
{title:"Butterfly (unidentified)",description:"unavailable is animal",user_id:2},
{title:"Cat, miner's",description:"Bassariscus astutus is animal",user_id:1},
{title:"Black-crowned night heron",description:"Nycticorax nycticorax is animal",user_id:7},
{title:"Two-banded monitor",description:"Varanus salvator is animal",user_id:5},
{title:"Parrot, hawk-headed",description:"Deroptyus accipitrinus is animal",user_id:8},
{title:"Brazilian otter",description:"Pteronura brasiliensis is animal",user_id:1},
{title:"Royal tern",description:"Thalasseus maximus is animal",user_id:8},
{title:"Beaver, eurasian",description:"Castor fiber is animal",user_id:7},
{title:"Woodcock, american",description:"Scolopax minor is animal",user_id:9},
{title:"Pocket gopher (unidentified)",description:"unavailable is animal",user_id:4},
{title:"Peacock, indian",description:"Pavo cristatus is animal",user_id:2},
{title:"Japanese macaque",description:"Macaca fuscata is animal",user_id:7},
{title:"Desert spiny lizard",description:"Sceloporus magister is animal",user_id:4},
{title:"Black-cheeked waxbill",description:"Estrilda erythronotos is animal",user_id:6},
{title:"Amazon parrot (unidentified)",description:"Amazona sp. is animal",user_id:6},
{title:"Cormorant, great",description:"Phalacrocorax carbo is animal",user_id:1},
{title:"Gray heron",description:"Ardea cinerea is animal",user_id:8},
{title:"Bonnet macaque",description:"Macaca radiata is animal",user_id:1},
{title:"Heron, green",description:"Butorides striatus is animal",user_id:4},
{title:"Swallow (unidentified)",description:"unavailable is animal",user_id:4},
{title:"Python, carpet",description:"Morelia spilotes variegata is animal",user_id:6},
{title:"Reindeer",description:"Rangifer tarandus is animal",user_id:8},
{title:"Porcupine, north american",description:"Erethizon dorsatum is animal",user_id:9},
{title:"Eastern box turtle",description:"Terrapene carolina is animal",user_id:5},
{title:"Kingfisher, white-throated",description:"Halcyon smyrnesis is animal",user_id:2},
{title:"Penguin, galapagos",description:"Spheniscus mendiculus is animal",user_id:3},
{title:"Rufous tree pie",description:"Dendrocitta vagabunda is animal",user_id:5},
{title:"Black and white colobus",description:"Colobus guerza is animal",user_id:7},
{title:"Creeper, black-tailed tree",description:"Climacteris melanura is animal",user_id:5},
{title:"Rose-ringed parakeet",description:"Psittacula krameri is animal",user_id:1},
{title:"Pie, indian tree",description:"Dendrocitta vagabunda is animal",user_id:8},
{title:"Blue-footed booby",description:"Sula nebouxii is animal",user_id:1},
{title:"Least chipmunk",description:"Eutamias minimus is animal",user_id:5},
{title:"Squirrel, european red",description:"Sciurus vulgaris is animal",user_id:4},
{title:"Sloth bear",description:"Melursus ursinus is animal",user_id:9},
{title:"Goose, egyptian",description:"Alopochen aegyptiacus is animal",user_id:7},
{title:"Wood pigeon",description:"Columba palumbus is animal",user_id:9},
{title:"Deer, white-tailed",description:"Odocoilenaus virginianus is animal",user_id:8},
{title:"Ibis, sacred",description:"Threskionis aethiopicus is animal",user_id:1},
{title:"Gorilla, western lowland",description:"Gorilla gorilla is animal",user_id:3},
{title:"Badger, eurasian",description:"Meles meles is animal",user_id:4},
{title:"Defassa waterbuck",description:"Kobus defassa is animal",user_id:1},
{title:"Elegant crested tinamou",description:"Eudromia elegans is animal",user_id:8},
{title:"Antechinus, brown",description:"Antechinus flavipes is animal",user_id:6},
{title:"African snake (unidentified)",description:"unavailable is animal",user_id:1},
{title:"Flamingo, chilean",description:"Phoenicopterus chilensis is animal",user_id:3},
{title:"Eagle, golden",description:"Aquila chrysaetos is animal",user_id:2},
{title:"Masked booby",description:"Sula dactylatra is animal",user_id:9},
{title:"Wallaby, whip-tailed",description:"Macropus parryi is animal",user_id:7},
{title:"Lemur, ring-tailed",description:"Lemur catta is animal",user_id:1},
{title:"Rhesus macaque",description:"Macaca mulatta is animal",user_id:2},
{title:"Tailless tenrec",description:"Tenrec ecaudatus is animal",user_id:8},
{title:"Steller's sea lion",description:"Eumetopias jubatus is animal",user_id:6},
{title:"Thrasher, curve-billed",description:"Toxostoma curvirostre is animal",user_id:5},
{title:"Cape wild cat",description:"Felis libyca is animal",user_id:8},
{title:"Bandicoot, short-nosed",description:"Isoodon obesulus is animal",user_id:1},
{title:"Leadbeateri's ground hornbill",description:"Bucorvus leadbeateri is animal",user_id:2},
{title:"Common dolphin",description:"Delphinus delphis is animal",user_id:2},
{title:"Macaque, japanese",description:"Macaca fuscata is animal",user_id:7},
{title:"African black crake",description:"Limnocorax flavirostra is animal",user_id:1},
{title:"White-nosed coatimundi",description:"Nasua narica is animal",user_id:9},
{title:"Emu",description:"Dromaeus novaehollandiae is animal",user_id:3},
{title:"Buffalo, wild water",description:"Bubalus arnee is animal",user_id:7},
{title:"Heron, green",description:"Butorides striatus is animal",user_id:8},
{title:"Javanese cormorant",description:"Phalacrocorax niger is animal",user_id:3},
{title:"Guanaco",description:"Lama guanicoe is animal",user_id:1},
{title:"Goose, knob-nosed",description:"Sarkidornis melanotos is animal",user_id:1},
{title:"Goose, greylag",description:"Anser anser is animal",user_id:5},
{title:"Butterfly, tropical buckeye",description:"Junonia genoveua is animal",user_id:4},
{title:"Boa, cook's tree",description:"Corallus hortulanus cooki is animal",user_id:5},
{title:"Giant armadillo",description:"Priodontes maximus is animal",user_id:8},
{title:"Pied butcher bird",description:"Cracticus nigroagularis is animal",user_id:7},
{title:"Viper, egyptian",description:"Naja haje is animal",user_id:9},
{title:"Caracal",description:"Felis caracal is animal",user_id:5},
{title:"Galapagos albatross",description:"Diomedea irrorata is animal",user_id:2},
{title:"Yellow mongoose",description:"Cynictis penicillata is animal",user_id:5},
{title:"Asiatic jackal",description:"Canis aureus is animal",user_id:4},
{title:"Yellow-billed hornbill",description:"Tockus flavirostris is animal",user_id:3},
{title:"Carmine bee-eater",description:"Merops nubicus is animal",user_id:3},
{title:"Crown of thorns starfish",description:"Acanthaster planci is animal",user_id:4},
{title:"Mocking cliffchat",description:"Thamnolaea cinnmomeiventris is animal",user_id:1},
{title:"Jacana, african",description:"Actophilornis africanus is animal",user_id:8},
{title:"Painted stork",description:"Mycteria leucocephala is animal",user_id:1},
{title:"Common genet",description:"Genetta genetta is animal",user_id:5},
{title:"Frogmouth, tawny",description:"Podargus strigoides is animal",user_id:5},
{title:"Kangaroo, jungle",description:"Macropus agilis is animal",user_id:7},
{title:"Tokay gecko",description:"Gekko gecko is animal",user_id:1},
{title:"Swainson's francolin",description:"Francolinus swainsonii is animal",user_id:2},
{title:"Wallaby, euro",description:"Macropus robustus is animal",user_id:7},
{title:"Tokay gecko",description:"Gekko gecko is animal",user_id:3},
{title:"Crowned hawk-eagle",description:"Spizaetus coronatus is animal",user_id:3},
{title:"Fox, crab-eating",description:"Dusicyon thous is animal",user_id:7},
{title:"Rhesus monkey",description:"Macaca mulatta is animal",user_id:3},
{title:"Little brown dove",description:"Streptopelia senegalensis is animal",user_id:1},
{title:"Black-tailed deer",description:"Odocoileus hemionus is animal",user_id:4},
{title:"Seal, northern fur",description:"Callorhinus ursinus is animal",user_id:1},
{title:"Red-cheeked cordon bleu",description:"Uraeginthus bengalus is animal",user_id:3},
{title:"Secretary bird",description:"Sagittarius serpentarius is animal",user_id:6},
{title:"Burchell's gonolek",description:"Laniaurius atrococcineus is animal",user_id:4},
{title:"Pelican, brown",description:"Pelecanus occidentalis is animal",user_id:9},
{title:"Starling, red-shouldered glossy",description:"Lamprotornis nitens is animal",user_id:9},
{title:"Asian elephant",description:"Elephas maximus bengalensis is animal",user_id:5},
{title:"Spider, wolf",description:"Lycosa godeffroyi is animal",user_id:2},
{title:"Caiman, spectacled",description:"Caiman crocodilus is animal",user_id:4},
{title:"Ring-tailed gecko",description:"Cyrtodactylus louisiadensis is animal",user_id:6},
{title:"Squirrel, eurasian red",description:"Sciurus vulgaris is animal",user_id:1},
{title:"Neotropic cormorant",description:"Phalacrocorax brasilianus is animal",user_id:4},
{title:"Bulbul, black-fronted",description:"Pycnonotus nigricans is animal",user_id:5},
{title:"Siskin, pine",description:"Carduelis pinus is animal",user_id:5},
{title:"European stork",description:"Ciconia ciconia is animal",user_id:3},
{title:"Parrot, hawk-headed",description:"Deroptyus accipitrinus is animal",user_id:2},
{title:"Striped hyena",description:"Hyaena hyaena is animal",user_id:7},
{title:"Black spider monkey",description:"Ateles paniscus is animal",user_id:9},
{title:"Langur, gray",description:"Semnopithecus entellus is animal",user_id:5},
{title:"Red phalarope",description:"Phalaropus fulicarius is animal",user_id:7},
{title:"Alligator, mississippi",description:"Alligator mississippiensis is animal",user_id:1},
{title:"Eagle owl (unidentified)",description:"Bubo sp. is animal",user_id:1},
{title:"Owl, snowy",description:"Nyctea scandiaca is animal",user_id:8},
{title:"African lion",description:"Panthera leo is animal",user_id:1},
{title:"Yellow-necked spurfowl",description:"Francolinus leucoscepus is animal",user_id:3},
{title:"Goose, snow",description:"Anser caerulescens is animal",user_id:2},
{title:"Blue catfish",description:"Ictalurus furcatus is animal",user_id:2},
{title:"Loris, slender",description:"Loris tardigratus is animal",user_id:1},
{title:"Marmot, yellow-bellied",description:"Marmota flaviventris is animal",user_id:7},
{title:"Gazer, sun",description:"Cordylus giganteus is animal",user_id:5},
{title:"Bulbul, black-fronted",description:"Pycnonotus nigricans is animal",user_id:8},
{title:"Black-backed jackal",description:"Canis mesomelas is animal",user_id:1},
{title:"Chestnut weaver",description:"Ploceus rubiginosus is animal",user_id:9},
{title:"Potoroo",description:"Potorous tridactylus is animal",user_id:3},
{title:"Caribou",description:"Rangifer tarandus is animal",user_id:9},
{title:"Dragon, asian water",description:"Physignathus cocincinus is animal",user_id:1},
{title:"Common grenadier",description:"Uraeginthus granatina is animal",user_id:2},
{title:"African elephant",description:"Loxodonta africana is animal",user_id:9},
{title:"Cape white-eye",description:"Zosterops pallidus is animal",user_id:6},
{title:"Asiatic wild ass",description:"Equus hemionus is animal",user_id:1},
{title:"Macaque, pig-tailed",description:"Macaca nemestrina is animal",user_id:3},
{title:"Bear, polar",description:"Ursus maritimus is animal",user_id:8},
{title:"Sandpiper, spotted wood",description:"Tringa glareola is animal",user_id:6},
{title:"Western lowland gorilla",description:"Gorilla gorilla is animal",user_id:7},
{title:"Osprey",description:"Pandon haliaetus is animal",user_id:3},
{title:"Thrasher, curve-billed",description:"Toxostoma curvirostre is animal",user_id:8},
{title:"Sheathbill, snowy",description:"Chionis alba is animal",user_id:6},
{title:"Lory, rainbow",description:"Trichoglossus haematodus moluccanus is animal",user_id:3},
{title:"Mouse, four-striped grass",description:"Rhabdomys pumilio is animal",user_id:5},
{title:"Potoroo",description:"Potorous tridactylus is animal",user_id:1},
{title:"Black-crowned crane",description:"Balearica pavonina is animal",user_id:4},
{title:"Indian giant squirrel",description:"Ratufa indica is animal",user_id:5},
{title:"Common ringtail",description:"Pseudocheirus peregrinus is animal",user_id:1},
{title:"Bengal vulture",description:"Gyps bengalensis is animal",user_id:1},
{title:"Rhesus monkey",description:"Macaca mulatta is animal",user_id:1},
{title:"European shelduck",description:"Tadorna tadorna is animal",user_id:4},
{title:"Kite, black",description:"Milvus migrans is animal",user_id:7},
{title:"Buttermilk snake",description:"Coluber constrictor is animal",user_id:1},
{title:"Magistrate black colobus",description:"Colobus guerza is animal",user_id:9},
{title:"Darter, african",description:"Anhinga rufa is animal",user_id:3},
{title:"Reindeer",description:"Rangifer tarandus is animal",user_id:1},
{title:"Galapagos albatross",description:"Diomedea irrorata is animal",user_id:9},
{title:"Common brushtail possum",description:"Trichosurus vulpecula is animal",user_id:6},
{title:"Common brushtail possum",description:"Trichosurus vulpecula is animal",user_id:5},
{title:"Squirrel, eastern fox",description:"Sciurus niger is animal",user_id:9},
{title:"Pied avocet",description:"Recurvirostra avosetta is animal",user_id:6},
{title:"Squirrel, eastern fox",description:"Sciurus niger is animal",user_id:1},
{title:"Jungle cat",description:"Felis chaus is animal",user_id:1},
{title:"Civet (unidentified)",description:"unavailable is animal",user_id:1},
{title:"Tern, white-winged",description:"Chlidonias leucopterus is animal",user_id:8},
{title:"Chuckwalla",description:"Sauromalus obesus is animal",user_id:6},
{title:"Owl, snowy",description:"Nyctea scandiaca is animal",user_id:8},
{title:"Whale, baleen",description:"Eubalaena australis is animal",user_id:5},
{title:"Lizard, goanna",description:"Varanus sp. is animal",user_id:6},
{title:"Langur, gray",description:"Semnopithecus entellus is animal",user_id:2},
{title:"Common wallaroo",description:"Macropus robustus is animal",user_id:1},
{title:"Booby, masked",description:"Sula dactylatra is animal",user_id:7},
{title:"Ground monitor (unidentified)",description:"Varanus sp. is animal",user_id:7},
{title:"Egret, great",description:"Casmerodius albus is animal",user_id:4},
{title:"Sugar glider",description:"Petaurus breviceps is animal",user_id:7},
{title:"Crow, american",description:"Corvus brachyrhynchos is animal",user_id:8},
{title:"Spotted wood sandpiper",description:"Tringa glareola is animal",user_id:6},
{title:"Banded mongoose",description:"Mungos mungo is animal",user_id:2},
{title:"Sulfur-crested cockatoo",description:"Cacatua galerita is animal",user_id:5},
{title:"Mocking cliffchat",description:"Thamnolaea cinnmomeiventris is animal",user_id:1},
{title:"Chilean flamingo",description:"Phoenicopterus chilensis is animal",user_id:6},
{title:"Wallaby, red-necked",description:"Macropus rufogriseus is animal",user_id:8},
{title:"Neotropic cormorant",description:"Phalacrocorax brasilianus is animal",user_id:1},
{title:"Chameleon (unidentified)",description:"Chamaelo sp. is animal",user_id:8},
{title:"Steller's sea lion",description:"Eumetopias jubatus is animal",user_id:1},
{title:"Ringtail",description:"Bassariscus astutus is animal",user_id:8},
{title:"Gulls (unidentified)",description:"Larus sp. is animal",user_id:6},
{title:"Oystercatcher, blackish",description:"Haematopus ater is animal",user_id:9},
{title:"Squirrel, eurasian red",description:"Sciurus vulgaris is animal",user_id:1},
{title:"Olive baboon",description:"Papio cynocephalus is animal",user_id:1},
{title:"Dove, ring",description:"Columba palumbus is animal",user_id:1},
{title:"Snake, racer",description:"Coluber constrictor is animal",user_id:9},
{title:"Seal, northern elephant",description:"Mirounga angustirostris is animal",user_id:9},
{title:"Sunbird, lesser double-collared",description:"Nectarinia chalybea is animal",user_id:4},
{title:"Tiger",description:"Panthera tigris is animal",user_id:4},
{title:"Common genet",description:"Genetta genetta is animal",user_id:2},
{title:"Deer, savannah",description:"Mazama gouazoubira is animal",user_id:9},
{title:"Plains zebra",description:"Equus burchelli is animal",user_id:3},
{title:"Monitor, white-throated",description:"Varanus albigularis is animal",user_id:8},
{title:"Carpet python",description:"Morelia spilotes variegata is animal",user_id:6},
{title:"Red hartebeest",description:"Alcelaphus buselaphus caama is animal",user_id:7},
{title:"Pallas's fish eagle",description:"Haliaeetus leucoryphus is animal",user_id:1},
{title:"Kingfisher, malachite",description:"Corythornis cristata is animal",user_id:8},
{title:"Sheep, american bighorn",description:"Ovis canadensis is animal",user_id:3},
{title:"Peacock, blue",description:"Pavo cristatus is animal",user_id:7},
{title:"Kangaroo, red",description:"Macropus rufus is animal",user_id:9},
{title:"Robin, kalahari scrub",description:"Certotrichas paena is animal",user_id:5},
{title:"Platypus",description:"Ornithorhynchus anatinus is animal",user_id:3},
{title:"Cobra (unidentified)",description:"Naja sp. is animal",user_id:1},
{title:"Gambel's quail",description:"Callipepla gambelii is animal",user_id:6},
{title:"Australian masked owl",description:"Tyto novaehollandiae is animal",user_id:1},
{title:"Grey fox",description:"Vulpes cinereoargenteus is animal",user_id:1},
{title:"Black-winged stilt",description:"Himantopus himantopus is animal",user_id:2},
{title:"Wapiti, elk,",description:"Cervus canadensis is animal",user_id:4},
{title:"Slender-billed cockatoo",description:"Cacatua tenuirostris is animal",user_id:3},
{title:"Australian masked owl",description:"Tyto novaehollandiae is animal",user_id:1},
{title:"White-cheeked pintail",description:"Anas bahamensis is animal",user_id:1},
{title:"Capuchin, weeper",description:"Cebus nigrivittatus is animal",user_id:9},
{title:"Tern, white-winged black",description:"Chlidonias leucopterus is animal",user_id:9},
{title:"Southern brown bandicoot",description:"Isoodon obesulus is animal",user_id:2},
{title:"Cobra (unidentified)",description:"Naja sp. is animal",user_id:5},
{title:"Grey fox",description:"Vulpes cinereoargenteus is animal",user_id:2},
{title:"Hawk, red-tailed",description:"Buteo jamaicensis is animal",user_id:8},
{title:"Worm snake (unidentified)",description:"Carphophis sp. is animal",user_id:3},
{title:"Square-lipped rhinoceros",description:"Ceratotherium simum is animal",user_id:8},
{title:"Parakeet, rose-ringed",description:"Psittacula krameri is animal",user_id:2},
{title:"Barking gecko",description:"Phylurus milli is animal",user_id:6},
{title:"Hottentot teal",description:"Anas punctata is animal",user_id:2},
{title:"African porcupine",description:"Hystrix cristata is animal",user_id:8},
{title:"Dove, little brown",description:"Streptopelia senegalensis is animal",user_id:6},
{title:"Crowned eagle",description:"Spizaetus coronatus is animal",user_id:1},
{title:"Spectacled caiman",description:"Caiman crocodilus is animal",user_id:3},
{title:"Gambel's quail",description:"Callipepla gambelii is animal",user_id:8},
{title:"Pygmy possum",description:"Acrobates pygmaeus is animal",user_id:8},
{title:"Francolin, swainson's",description:"Francolinus swainsonii is animal",user_id:7},
{title:"Vine snake (unidentified)",description:"Oxybelis sp. is animal",user_id:5},
{title:"Zorro, common",description:"Dusicyon thous is animal",user_id:4},
{title:"Nutcracker, clark's",description:"Nucifraga columbiana is animal",user_id:6},
{title:"Siskin, pine",description:"Carduelis pinus is animal",user_id:1},
{title:"Wild boar",description:"Sus scrofa is animal",user_id:8},
{title:"White-bellied sea eagle",description:"Haliaetus leucogaster is animal",user_id:7},
{title:"Levaillant's barbet",description:"Trachyphonus vaillantii is animal",user_id:2},
{title:"Frog (unidentified)",description:"Rana sp. is animal",user_id:8},
{title:"Pheasant, common",description:"Phasianus colchicus is animal",user_id:6},
{title:"Dolphin, common",description:"Delphinus delphis is animal",user_id:4},
{title:"Crane, wattled",description:"Bugeranus caruncalatus is animal",user_id:9},
{title:"Cattle egret",description:"Bubulcus ibis is animal",user_id:3},
{title:"Australian pelican",description:"Pelecanus conspicillatus is animal",user_id:5},
{title:"Field flicker",description:"Colaptes campestroides is animal",user_id:2},
{title:"Macaque, rhesus",description:"Macaca mulatta is animal",user_id:5},
{title:"Small-clawed otter",description:"Aonyx cinerea is animal",user_id:4},
{title:"Boa, cook's tree",description:"Corallus hortulanus cooki is animal",user_id:4},
{title:"Baboon, gelada",description:"Theropithecus gelada is animal",user_id:1},
{title:"Francolin, coqui",description:"Francolinus coqui is animal",user_id:8},
{title:"Great cormorant",description:"Phalacrocorax carbo is animal",user_id:3},
{title:"Rose-ringed parakeet",description:"Psittacula krameri is animal",user_id:8},
{title:"Tern, white-winged black",description:"Chlidonias leucopterus is animal",user_id:8},
{title:"Antelope, roan",description:"Hippotragus equinus is animal",user_id:9},
{title:"Common nighthawk",description:"Chordeiles minor is animal",user_id:5},
{title:"Porcupine, crested",description:"Hystrix cristata is animal",user_id:7},
{title:"Antelope, sable",description:"Hippotragus niger is animal",user_id:3},
{title:"Lizard (unidentified)",description:"unavailable is animal",user_id:5},
{title:"Cattle egret",description:"Bubulcus ibis is animal",user_id:2},
{title:"Tamandua, southern",description:"Tamandua tetradactyla is animal",user_id:2},
{title:"African elephant",description:"Loxodonta africana is animal",user_id:4},
{title:"Long-tailed spotted cat",description:"Felis wiedi or Leopardus weidi is animal",user_id:1},
{title:"Yellow-throated sandgrouse",description:"Pterocles gutturalis is animal",user_id:1},
{title:"Waxbill, blue",description:"Uraeginthus angolensis is animal",user_id:9},
{title:"Hawk, galapagos",description:"Buteo galapagoensis is animal",user_id:8},
{title:"Sandpiper, spotted wood",description:"Tringa glareola is animal",user_id:4},
{title:"Asian false vampire bat",description:"Megaderma spasma is animal",user_id:1},
{title:"Red-shouldered glossy starling",description:"Lamprotornis nitens is animal",user_id:5},
{title:"Small-clawed otter",description:"Aonyx cinerea is animal",user_id:2},
{title:"Striped skunk",description:"Mephitis mephitis is animal",user_id:7},
{title:"Oriental white-backed vulture",description:"Gyps bengalensis is animal",user_id:6},
{title:"Snake, western patch-nosed",description:"Salvadora hexalepis is animal",user_id:8},
{title:"Long-finned pilot whale",description:"Globicephala melas is animal",user_id:3},
{title:"Mississippi alligator",description:"Alligator mississippiensis is animal",user_id:2},
{title:"Lilac-breasted roller",description:"Coracias caudata is animal",user_id:1},
{title:"Insect, stick",description:"Leprocaulinus vipera is animal",user_id:7},
{title:"Badger, american",description:"Taxidea taxus is animal",user_id:6},
{title:"Brown antechinus",description:"Antechinus flavipes is animal",user_id:9},
{title:"Heron, boat-billed",description:"Cochlearius cochlearius is animal",user_id:2},
{title:"Spur-winged goose",description:"Plectopterus gambensis is animal",user_id:3},
{title:"Dove, rock",description:"Columba livia is animal",user_id:5},
{title:"Long-billed corella",description:"Cacatua tenuirostris is animal",user_id:1},
{title:"Red-billed tropic bird",description:"Phaethon aethereus is animal",user_id:1},
{title:"Squirrel glider",description:"Petaurus norfolcensis is animal",user_id:8},
{title:"Baboon, olive",description:"Papio cynocephalus is animal",user_id:1},
{title:"Wallaby, tammar",description:"Macropus eugenii is animal",user_id:1},
{title:"Vulture, turkey",description:"Cathartes aura is animal",user_id:5},
{title:"Porcupine, prehensile-tailed",description:"Coendou prehensilis is animal",user_id:2},
{title:"North American river otter",description:"Lutra canadensis is animal",user_id:1},
{title:"Lizard (unidentified)",description:"unavailable is animal",user_id:8},
{title:"Yellow-necked spurfowl",description:"Francolinus leucoscepus is animal",user_id:1},
{title:"Blesbok",description:"Damaliscus dorcas is animal",user_id:5},
{title:"Coatimundi, ring-tailed",description:"Nasua nasua is animal",user_id:9},
{title:"White-browed owl",description:"Ninox superciliaris is animal",user_id:6},
{title:"American bighorn sheep",description:"Ovis canadensis is animal",user_id:5},
{title:"Cook's tree boa",description:"Corallus hortulanus cooki is animal",user_id:1},
{title:"Whale, southern right",description:"Eubalaena australis is animal",user_id:2},
{title:"Crake, african black",description:"Limnocorax flavirostra is animal",user_id:5},
{title:"Eagle, white-bellied sea",description:"Haliaetus leucogaster is animal",user_id:1},
{title:"Canadian river otter",description:"Lutra canadensis is animal",user_id:1},
{title:"Collared lemming",description:"Dicrostonyx groenlandicus is animal",user_id:7},
{title:"Vulture, lappet-faced",description:"Aegypius tracheliotus is animal",user_id:6},
{title:"Alpaca",description:"Lama pacos is animal",user_id:5},
{title:"Bettong, brush-tailed",description:"Bettongia penicillata is animal",user_id:5},
{title:"Pig-tailed macaque",description:"Macaca nemestrina is animal",user_id:8},
{title:"Lizard, desert spiny",description:"Sceloporus magister is animal",user_id:1},
{title:"Lemur, sportive",description:"Lepilemur rufescens is animal",user_id:1},
{title:"Boar, wild",description:"Sus scrofa is animal",user_id:8},
{title:"Puna ibis",description:"Plegadis ridgwayi is animal",user_id:2},
{title:"American bison",description:"Bison bison is animal",user_id:1},
{title:"Dolphin, common",description:"Delphinus delphis is animal",user_id:9},
{title:"Jungle kangaroo",description:"Macropus agilis is animal",user_id:4},
{title:"Macaw, red and blue",description:"Ara chloroptera is animal",user_id:5},
{title:"Mountain lion",description:"Felis concolor is animal",user_id:7},
{title:"Crane, black-crowned",description:"Balearica pavonina is animal",user_id:3},
{title:"Red-billed tropic bird",description:"Phaethon aethereus is animal",user_id:5},
{title:"Greater adjutant stork",description:"Leptoptilus dubius is animal",user_id:2},
{title:"Brush-tailed bettong",description:"Bettongia penicillata is animal",user_id:2},
{title:"Corella, long-billed",description:"Cacatua tenuirostris is animal",user_id:1},
{title:"Corella, long-billed",description:"Cacatua tenuirostris is animal",user_id:5},
{title:"Caracal",description:"Felis caracal is animal",user_id:1},
{title:"Magistrate black colobus",description:"Colobus guerza is animal",user_id:3},
{title:"White spoonbill",description:"Platalea leucordia is animal",user_id:6},
{title:"Black-necked stork",description:"Ephippiorhynchus mycteria is animal",user_id:8},
{title:"Long-necked turtle",description:"Chelodina longicollis is animal",user_id:8},
{title:"Flying fox (unidentified)",description:"unavailable is animal",user_id:4},
{title:"White-lipped peccary",description:"Tayassu pecari is animal",user_id:5},
{title:"Lizard, frilled",description:"Chlamydosaurus kingii is animal",user_id:2},
{title:"Three-banded plover",description:"Charadrius tricollaris is animal",user_id:5},
{title:"Bottle-nose dolphin",description:"Tursiops truncatus is animal",user_id:4},
{title:"Antelope, sable",description:"Hippotragus niger is animal",user_id:8},
{title:"Zebra, common",description:"Equus burchelli is animal",user_id:5},
{title:"American bighorn sheep",description:"Ovis canadensis is animal",user_id:1},
{title:"Wild boar",description:"Sus scrofa is animal",user_id:1},
{title:"Asian foreset tortoise",description:"Manouria emys is animal",user_id:1},
{title:"Swan, trumpeter",description:"Cygnus buccinator is animal",user_id:6},
{title:"Oriental white-backed vulture",description:"Gyps bengalensis is animal",user_id:4},
{title:"Red-necked wallaby",description:"Macropus rufogriseus is animal",user_id:6},
{title:"Tapir, brazilian",description:"Tapirus terrestris is animal",user_id:2},
{title:"Dog, african wild",description:"Lycaon pictus is animal",user_id:8},
{title:"Western palm tanager (unidentified)",description:"unavailable is animal",user_id:1},
{title:"Meerkat, red",description:"Cynictis penicillata is animal",user_id:9},
{title:"Indian leopard",description:"Panthera pardus is animal",user_id:4},
{title:"Grey fox",description:"Vulpes cinereoargenteus is animal",user_id:9},
{title:"Timber wolf",description:"Canis lupus lycaon is animal",user_id:9},
{title:"Beisa oryx",description:"Oryx gazella is animal",user_id:2},
{title:"Red-winged hawk (unidentified)",description:"unavailable is animal",user_id:8},
{title:"Eurasian hoopoe",description:"Upupa epops is animal",user_id:3},
{title:"Killer whale",description:"Orcinus orca is animal",user_id:5},
{title:"Western grey kangaroo",description:"Macropus fuliginosus is animal",user_id:5},
{title:"Eleven-banded armadillo (unidentified)",description:"Cabassous sp. is animal",user_id:2},
{title:"Parrot, hawk-headed",description:"Deroptyus accipitrinus is animal",user_id:2},
{title:"Two-toed tree sloth",description:"Choloepus hoffmani is animal",user_id:1},
{title:"Oryx, beisa",description:"Oryx gazella is animal",user_id:3},
{title:"Dusky rattlesnake",description:"Crotalus triseriatus is animal",user_id:7},
{title:"Blacksmith plover",description:"Vanellus armatus is animal",user_id:2},
{title:"Red-knobbed coot",description:"Fulica cristata is animal",user_id:3},
{title:"Egret, great",description:"Casmerodius albus is animal",user_id:4},
{title:"Goose, andean",description:"Chloephaga melanoptera is animal",user_id:7},
{title:"Hawk, galapagos",description:"Buteo galapagoensis is animal",user_id:6},
{title:"American racer",description:"Coluber constrictor is animal",user_id:9},
{title:"Woodpecker, downy",description:"Picoides pubescens is animal",user_id:5},
{title:"Water moccasin",description:"Agkistrodon piscivorus is animal",user_id:4},
{title:"Falcon, prairie",description:"Falco mexicanus is animal",user_id:2},
{title:"Deer, barasingha",description:"Cervus duvauceli is animal",user_id:5},
{title:"Puna ibis",description:"Plegadis ridgwayi is animal",user_id:5},
{title:"Fork-tailed drongo",description:"Dicrurus adsimilis is animal",user_id:1},
{title:"Egyptian goose",description:"Alopochen aegyptiacus is animal",user_id:1},
{title:"Buttermilk snake",description:"Coluber constrictor is animal",user_id:7},
{title:"Fisher",description:"Martes pennanti is animal",user_id:2},
{title:"Godwit, hudsonian",description:"Limosa haemastica is animal",user_id:5},
{title:"Crane, sarus",description:"Grus antigone is animal",user_id:1},
{title:"Pie, indian tree",description:"Dendrocitta vagabunda is animal",user_id:7},
{title:"Red deer",description:"Cervus elaphus is animal",user_id:9},
{title:"Heron, green",description:"Butorides striatus is animal",user_id:7},
{title:"Rat, desert kangaroo",description:"Dipodomys deserti is animal",user_id:1},
{title:"Waved albatross",description:"Diomedea irrorata is animal",user_id:1},
{title:"Monkey, rhesus",description:"Macaca mulatta is animal",user_id:3},
{title:"Cattle egret",description:"Bubulcus ibis is animal",user_id:3},
{title:"Quoll, eastern",description:"Dasyurus viverrinus is animal",user_id:4},
{title:"Impala",description:"Aepyceros mylampus is animal",user_id:1},
{title:"Squirrel, golden-mantled ground",description:"Spermophilus lateralis is animal",user_id:4},
{title:"Dove, emerald-spotted wood",description:"Turtur chalcospilos is animal",user_id:8},
{title:"Malachite kingfisher",description:"Corythornis cristata is animal",user_id:4},
{title:"Slender-billed cockatoo",description:"Cacatua tenuirostris is animal",user_id:1},
{title:"Mourning collared dove",description:"Streptopelia decipiens is animal",user_id:4},
{title:"Vervet monkey",description:"Cercopithecus aethiops is animal",user_id:8},
{title:"Gorilla, western lowland",description:"Gorilla gorilla is animal",user_id:4},
{title:"Common raccoon",description:"Procyon lotor is animal",user_id:5},
{title:"Tern, white-winged black",description:"Chlidonias leucopterus is animal",user_id:5},
{title:"Cormorant, little",description:"Phalacrocorax niger is animal",user_id:1},
{title:"Bison, american",description:"Bison bison is animal",user_id:5},
{title:"Black-crowned crane",description:"Balearica pavonina is animal",user_id:8},
{title:"Weaver, red-billed buffalo",description:"Bubalornis niger is animal",user_id:7},
{title:"Crow, pied",description:"Corvus albus is animal",user_id:9},
{title:"Pied crow",description:"Corvus albus is animal",user_id:5},
{title:"Eagle, white-bellied sea",description:"Haliaetus leucogaster is animal",user_id:2},
{title:"Genet, small-spotted",description:"Genetta genetta is animal",user_id:2},
{title:"Giant girdled lizard",description:"Cordylus giganteus is animal",user_id:1},
{title:"Wallaby, whip-tailed",description:"Macropus parryi is animal",user_id:8},
{title:"Komodo dragon",description:"Varanus komodensis is animal",user_id:3},
{title:"Grouse, sage",description:"Centrocercus urophasianus is animal",user_id:1},
{title:"American badger",description:"Taxidea taxus is animal",user_id:6},
{title:"Least chipmunk",description:"Eutamias minimus is animal",user_id:2},
{title:"Eagle owl (unidentified)",description:"Bubo sp. is animal",user_id:8},
{title:"Chuckwalla",description:"Sauromalus obesus is animal",user_id:2},
{title:"Falcon, prairie",description:"Falco mexicanus is animal",user_id:1},
{title:"Camel, dromedary",description:"Camelus dromedarius is animal",user_id:4},
{title:"African black crake",description:"Limnocorax flavirostra is animal",user_id:1},
{title:"Pig-tailed macaque",description:"Macaca nemestrina is animal",user_id:2},
{title:"Antechinus, brown",description:"Antechinus flavipes is animal",user_id:7},
{title:"Thomson's gazelle",description:"Gazella thompsonii is animal",user_id:1},
{title:"Baboon, chacma",description:"Papio ursinus is animal",user_id:9},
{title:"Eastern indigo snake",description:"Drymarchon corias couperi is animal",user_id:2},
{title:"Small-toothed palm civet",description:"Arctogalidia trivirgata is animal",user_id:2},
{title:"Screamer, crested",description:"Chauna torquata is animal",user_id:9},
{title:"Quail, gambel's",description:"Callipepla gambelii is animal",user_id:4},
{title:"Lemur, grey mouse",description:"Microcebus murinus is animal",user_id:9},
{title:"Gemsbok",description:"Oryx gazella is animal",user_id:1},
{title:"Brolga crane",description:"Grus rubicundus is animal",user_id:7},
{title:"Little brown dove",description:"Streptopelia senegalensis is animal",user_id:5},
{title:"Macaque, bonnet",description:"Macaca radiata is animal",user_id:9},
{title:"White-throated kingfisher",description:"Halcyon smyrnesis is animal",user_id:5},
{title:"African black crake",description:"Limnocorax flavirostra is animal",user_id:7},
{title:"Barrows goldeneye",description:"Bucephala clangula is animal",user_id:4},
{title:"White-winged black tern",description:"Chlidonias leucopterus is animal",user_id:9},
{title:"Southern lapwing",description:"Vanellus chilensis is animal",user_id:7},
{title:"Richardson's ground squirrel",description:"Spermophilus richardsonii is animal",user_id:2},
{title:"Egyptian vulture",description:"Neophron percnopterus is animal",user_id:1},
{title:"Cottonmouth",description:"Agkistrodon piscivorus is animal",user_id:2},
{title:"Rufous-collared sparrow",description:"Zonotrichia capensis is animal",user_id:6},
{title:"Elephant, asian",description:"Elephas maximus bengalensis is animal",user_id:3},
{title:"Striated heron",description:"Butorides striatus is animal",user_id:1},
{title:"Turaco, violet-crested",description:"Tauraco porphyrelophus is animal",user_id:3},
{title:"Tortoise, indian star",description:"Geochelone elegans is animal",user_id:1},
{title:"Crane, stanley",description:"Anthropoides paradisea is animal",user_id:6},
{title:"Shrew, mandras tree",description:"Anathana ellioti is animal",user_id:5},
{title:"Red kangaroo",description:"Macropus rufus is animal",user_id:8},
{title:"Monitor, water",description:"Varanus salvator is animal",user_id:7},
{title:"African black crake",description:"Limnocorax flavirostra is animal",user_id:5},
{title:"Red-billed toucan",description:"Ramphastos tucanus is animal",user_id:4},
{title:"Tayra",description:"Eira barbata is animal",user_id:1},
{title:"Grey fox",description:"Vulpes cinereoargenteus is animal",user_id:1},
{title:"Starling, superb",description:"Lamprotornis superbus is animal",user_id:8},
{title:"Verreaux's sifaka",description:"Propithecus verreauxi is animal",user_id:6},
{title:"Turtle (unidentified)",description:"unavailable is animal",user_id:2},
{title:"Dog, raccoon",description:"Nyctereutes procyonoides is animal",user_id:7},
{title:"Salmon pink bird eater tarantula",description:"Lasiodora parahybana is animal",user_id:9},
{title:"Little brown dove",description:"Streptopelia senegalensis is animal",user_id:2},
{title:"Malay squirrel (unidentified)",description:"unavailable is animal",user_id:2},
{title:"Galapagos hawk",description:"Buteo galapagoensis is animal",user_id:2},
{title:"Rufous-collared sparrow",description:"Zonotrichia capensis is animal",user_id:8},
{title:"Lory, rainbow",description:"Trichoglossus haematodus moluccanus is animal",user_id:8},
{title:"Partridge, coqui",description:"Francolinus coqui is animal",user_id:1},
{title:"Burchell's gonolek",description:"Laniaurius atrococcineus is animal",user_id:1},
{title:"Polecat, african",description:"Ictonyx striatus is animal",user_id:3},
{title:"Peccary, white-lipped",description:"Tayassu pecari is animal",user_id:9},
{title:"Wild boar",description:"Sus scrofa is animal",user_id:1},
{title:"Bonnet macaque",description:"Macaca radiata is animal",user_id:4},
{title:"Nile crocodile",description:"Crocodylus niloticus is animal",user_id:9},
{title:"Collared lemming",description:"Dicrostonyx groenlandicus is animal",user_id:7},
{title:"South American puma",description:"Felis concolor is animal",user_id:7},
{title:"Crab (unidentified)",description:"unavailable is animal",user_id:9},
{title:"Wallaby, whip-tailed",description:"Macropus parryi is animal",user_id:6},
{title:"Common nighthawk",description:"Chordeiles minor is animal",user_id:4},
{title:"Common ringtail",description:"Pseudocheirus peregrinus is animal",user_id:3},
{title:"Wombat, common",description:"Vombatus ursinus is animal",user_id:4},
{title:"Greater kudu",description:"Tragelaphus strepsiceros is animal",user_id:1},
{title:"Cormorant, little",description:"Phalacrocorax niger is animal",user_id:1},
{title:"Mocking cliffchat",description:"Thamnolaea cinnmomeiventris is animal",user_id:5},
{title:"Albatross, galapagos 2",description:"Diomedea irrorata is animal",user_id:7},
{title:"Deer, spotted",description:"Axis axis is animal",user_id:7},
{title:"Mynah, common",description:"Acridotheres tristis is animal",user_id:4},
{title:"Indian jackal",description:"Canis aureus is animal",user_id:9},
{title:"Fox, bat-eared",description:"Otocyon megalotis is animal",user_id:3},
{title:"Mongoose, banded",description:"Mungos mungo is animal",user_id:9},
{title:"King vulture",description:"Sarcorhamphus papa is animal",user_id:5},
{title:"Frilled lizard",description:"Chlamydosaurus kingii is animal",user_id:1},
{title:"Baboon, savanna",description:"Papio cynocephalus is animal",user_id:6},
{title:"Southern lapwing",description:"Vanellus chilensis is animal",user_id:6},
{title:"Vulture, lappet-faced",description:"Aegypius tracheliotus is animal",user_id:4},
{title:"Buttermilk snake",description:"Coluber constrictor is animal",user_id:2},
{title:"Fox, grey",description:"Vulpes cinereoargenteus is animal",user_id:4},
{title:"Cormorant, great",description:"Phalacrocorax carbo is animal",user_id:5},
{title:"Savannah deer",description:"Mazama gouazoubira is animal",user_id:7},
{title:"Cockatoo, roseate",description:"Eolophus roseicapillus is animal",user_id:3},
{title:"Heron, green",description:"Butorides striatus is animal",user_id:6},
{title:"Stilt, black-winged",description:"Himantopus himantopus is animal",user_id:2},
{title:"Columbian rainbow boa",description:"Epicrates cenchria maurus is animal",user_id:6},
{title:"Salmon pink bird eater tarantula",description:"Lasiodora parahybana is animal",user_id:4},
{title:"Grey heron",description:"Ardea cinerea is animal",user_id:3},
{title:"Turkey, australian brush",description:"Alectura lathami is animal",user_id:7},
{title:"Monkey, red howler",description:"Alouatta seniculus is animal",user_id:5},
{title:"Lion, steller's sea",description:"Eumetopias jubatus is animal",user_id:3},
{title:"Kori bustard",description:"Choriotis kori is animal",user_id:7},
{title:"Praying mantis (unidentified)",description:"unavailable is animal",user_id:8},
{title:"Gray duiker",description:"Sylvicapra grimma is animal",user_id:2},
{title:"Burmese brown mountain tortoise",description:"Manouria emys is animal",user_id:1},
{title:"White spoonbill",description:"Platalea leucordia is animal",user_id:1},
{title:"Pintail, bahama",description:"Anas bahamensis is animal",user_id:7},
{title:"Heron, black-crowned night",description:"Nycticorax nycticorax is animal",user_id:3},
{title:"Sheep, american bighorn",description:"Ovis canadensis is animal",user_id:7},
{title:"Prairie falcon",description:"Falco mexicanus is animal",user_id:1},
{title:"Partridge, coqui",description:"Francolinus coqui is animal",user_id:2},
{title:"Stork, marabou",description:"Leptoptilos crumeniferus is animal",user_id:4},
{title:"Cat, european wild",description:"Felis silvestris lybica is animal",user_id:4},
{title:"Common eland",description:"Taurotagus oryx is animal",user_id:5},
{title:"Duck, white-faced whistling",description:"Dendrocygna viduata is animal",user_id:6},
{title:"Racer, blue",description:"Coluber constrictor foxii is animal",user_id:6},
{title:"Barking gecko",description:"Phylurus milli is animal",user_id:6},
{title:"Jaeger, long-tailed",description:"Stercorarius longicausus is animal",user_id:1},
{title:"Owl, burrowing",description:"Speotyte cuniculata is animal",user_id:2},
{title:"Macaque, rhesus",description:"Macaca mulatta is animal",user_id:2},
{title:"Wombat, common",description:"Vombatus ursinus is animal",user_id:8},
{title:"Superb starling",description:"Lamprotornis superbus is animal",user_id:2},
{title:"American bighorn sheep",description:"Ovis canadensis is animal",user_id:7},
{title:"Dove, rock",description:"Columba livia is animal",user_id:7},
{title:"Hoary marmot",description:"Marmota caligata is animal",user_id:1},
{title:"Bustard, denham's",description:"Neotis denhami is animal",user_id:7},
{title:"Coqui partridge",description:"Francolinus coqui is animal",user_id:9},
{title:"Zorro, common",description:"Dusicyon thous is animal",user_id:9},
{title:"Yellow-throated sandgrouse",description:"Pterocles gutturalis is animal",user_id:7},
{title:"South American meadowlark (unidentified)",description:"unavailable is animal",user_id:6},
{title:"Spoonbill, white",description:"Platalea leucordia is animal",user_id:9},
{title:"Rufous-collared sparrow",description:"Zonotrichia capensis is animal",user_id:4},
{title:"Blackish oystercatcher",description:"Haematopus ater is animal",user_id:1},
{title:"African darter",description:"Anhinga rufa is animal",user_id:9},
{title:"Steller sea lion",description:"Eumetopias jubatus is animal",user_id:2},
{title:"Malay squirrel (unidentified)",description:"unavailable is animal",user_id:4},
{title:"Lizard (unidentified)",description:"unavailable is animal",user_id:1},
{title:"Brazilian otter",description:"Pteronura brasiliensis is animal",user_id:3},
{title:"Roadrunner, greater",description:"Geococcyx californianus is animal",user_id:6},
{title:"Cobra, egyptian",description:"Naja haje is animal",user_id:8},
{title:"Common turkey",description:"Meleagris gallopavo is animal",user_id:2},
{title:"Fox, asian red",description:"Vulpes vulpes is animal",user_id:5},
{title:"Blue and yellow macaw",description:"Ara ararauna is animal",user_id:4},
{title:"Giant anteater",description:"Myrmecophaga tridactyla is animal",user_id:3},
{title:"Kongoni",description:"Alcelaphus buselaphus cokii is animal",user_id:6},
{title:"Southern black-backed gull",description:"Larus dominicanus is animal",user_id:1},
{title:"African clawless otter",description:"Aonyx capensis is animal",user_id:1},
{title:"Blackish oystercatcher",description:"Haematopus ater is animal",user_id:1},
{title:"Superb starling",description:"Lamprotornis superbus is animal",user_id:1},
{title:"Egret, cattle",description:"Bubulcus ibis is animal",user_id:9},
{title:"Emerald-spotted wood dove",description:"Turtur chalcospilos is animal",user_id:7},
{title:"Emerald-spotted wood dove",description:"Turtur chalcospilos is animal",user_id:4},
{title:"Frilled dragon",description:"Chlamydosaurus kingii is animal",user_id:8},
{title:"Shelduck, common",description:"Tadorna tadorna is animal",user_id:6},
{title:"Dog, african wild",description:"Lycaon pictus is animal",user_id:9},
{title:"Black curlew",description:"Haematopus ater is animal",user_id:6},
{title:"Skink, african",description:"Mabuya spilogaster is animal",user_id:3},
{title:"Water moccasin",description:"Agkistrodon piscivorus is animal",user_id:7},
{title:"Heron, little",description:"Butorides striatus is animal",user_id:8},
{title:"Spectacled caiman",description:"Caiman crocodilus is animal",user_id:5},
{title:"Squirrel, arctic ground",description:"Spermophilus parryii is animal",user_id:5},
{title:"Kookaburra, laughing",description:"Dacelo novaeguineae is animal",user_id:9},
{title:"Bandicoot, southern brown",description:"Isoodon obesulus is animal",user_id:8},
{title:"Eurasian badger",description:"Meles meles is animal",user_id:1},
{title:"Turaco, violet-crested",description:"Tauraco porphyrelophus is animal",user_id:1},
{title:"Tokay gecko",description:"Gekko gecko is animal",user_id:6},
{title:"Eagle owl (unidentified)",description:"Bubo sp. is animal",user_id:7},
{title:"Sulfur-crested cockatoo",description:"Cacatua galerita is animal",user_id:4},
{title:"Roan antelope",description:"Hippotragus equinus is animal",user_id:8},
{title:"Admiral, indian red",description:"Vanessa indica is animal",user_id:7},
{title:"Lechwe, kafue flats",description:"Kobus leche robertsi is animal",user_id:3},
{title:"Ibis, sacred",description:"Threskionis aethiopicus is animal",user_id:1},
{title:"White-winged tern",description:"Chlidonias leucopterus is animal",user_id:1},
{title:"Falcon, peregrine",description:"Falco peregrinus is animal",user_id:4},
{title:"Heron, goliath",description:"Ardea golieth is animal",user_id:5},
{title:"Golden jackal",description:"Canis aureus is animal",user_id:1},
{title:"Raccoon dog",description:"Nyctereutes procyonoides is animal",user_id:1},
{title:"Bottle-nose dolphin",description:"Tursiops truncatus is animal",user_id:7},
{title:"Defassa waterbuck",description:"Kobus defassa is animal",user_id:4},
{title:"Marine iguana",description:"Amblyrhynchus cristatus is animal",user_id:7},
{title:"Scottish highland cow",description:"Bos taurus is animal",user_id:6},
{title:"Yellow-throated sandgrouse",description:"Pterocles gutturalis is animal",user_id:6},
{title:"Potoroo",description:"Potorous tridactylus is animal",user_id:9},
{title:"Blue crane",description:"Anthropoides paradisea is animal",user_id:5},
{title:"Levaillant's barbet",description:"Trachyphonus vaillantii is animal",user_id:9},
{title:"Dik, kirk's dik",description:"Madoqua kirkii is animal",user_id:4},
{title:"White-eye, cape",description:"Zosterops pallidus is animal",user_id:2},
{title:"White-necked raven",description:"Corvus albicollis is animal",user_id:3},
{title:"Savannah deer",description:"Mazama gouazoubira is animal",user_id:1},
{title:"Curlew, black",description:"Haematopus ater is animal",user_id:2},
{title:"Flicker, campo",description:"Colaptes campestroides is animal",user_id:3},
{title:"Porcupine, african",description:"Hystrix cristata is animal",user_id:7},
{title:"Blue shark",description:"Prionace glauca is animal",user_id:1},
{title:"Common rhea",description:"Rhea americana is animal",user_id:9},
{title:"Coot, red-knobbed",description:"Fulica cristata is animal",user_id:8},
{title:"American badger",description:"Taxidea taxus is animal",user_id:8},
{title:"Snake (unidentified)",description:"unavailable is animal",user_id:6},
{title:"White-eye, cape",description:"Zosterops pallidus is animal",user_id:1},
{title:"Sloth bear",description:"Melursus ursinus is animal",user_id:6},
{title:"Bee-eater (unidentified)",description:"Merops sp. is animal",user_id:7},
{title:"Common wallaroo",description:"Macropus robustus is animal",user_id:4},
{title:"Bat, asian false vampire",description:"Megaderma spasma is animal",user_id:4},
{title:"African wild cat",description:"Felis silvestris lybica is animal",user_id:2},
{title:"Macaque, rhesus",description:"Macaca mulatta is animal",user_id:8},
{title:"White-tailed jackrabbit",description:"Lepus townsendii is animal",user_id:6},
{title:"Lizard, collared",description:"Crotaphytus collaris is animal",user_id:6},
{title:"Egyptian viper",description:"Naja haje is animal",user_id:9},
{title:"Horned puffin",description:"Fratercula corniculata is animal",user_id:3},
{title:"Macaque, rhesus",description:"Macaca mulatta is animal",user_id:1},
{title:"Ring-tailed possum",description:"Pseudocheirus peregrinus is animal",user_id:3},
{title:"Grey lourie",description:"Lorythaixoides concolor is animal",user_id:2},
{title:"Sunbird, lesser double-collared",description:"Nectarinia chalybea is animal",user_id:1},
{title:"Rainbow lory",description:"Trichoglossus haematodus moluccanus is animal",user_id:6},
{title:"Springbok",description:"Antidorcas marsupialis is animal",user_id:7},
{title:"African jacana",description:"Actophilornis africanus is animal",user_id:2},
{title:"Potoroo",description:"Potorous tridactylus is animal",user_id:9},
{title:"Gelada baboon",description:"Theropithecus gelada is animal",user_id:3},
{title:"Python, carpet",description:"Morelia spilotes variegata is animal",user_id:6},
{title:"Blue-tongued lizard",description:"Tiliqua scincoides is animal",user_id:3},
{title:"Seal, southern elephant",description:"Mirounga leonina is animal",user_id:5},
{title:"Horned lark",description:"Eremophila alpestris is animal",user_id:6},
{title:"Sandgrouse, yellow-throated",description:"Pterocles gutturalis is animal",user_id:9},
{title:"Chuckwalla",description:"Sauromalus obesus is animal",user_id:7},
{title:"Pallas's fish eagle",description:"Haliaeetus leucoryphus is animal",user_id:9},
{title:"Adouri (unidentified)",description:"unavailable is animal",user_id:8},
{title:"Black bear",description:"Ursus americanus is animal",user_id:6},
{title:"Armadillo, seven-banded",description:"Dasypus septemcincus is animal",user_id:7},
{title:"White-faced whistling duck",description:"Dendrocygna viduata is animal",user_id:1},
{title:"African pied wagtail",description:"Motacilla aguimp is animal",user_id:6},
{title:"Robin, kalahari scrub",description:"Certotrichas paena is animal",user_id:9},
{title:"Koala",description:"Phascolarctos cinereus is animal",user_id:8},
{title:"Common genet",description:"Genetta genetta is animal",user_id:8},
{title:"Gecko, tokay",description:"Gekko gecko is animal",user_id:7},
{title:"Eagle, bald",description:"Haliaeetus leucocephalus is animal",user_id:1},
{title:"Wild turkey",description:"Meleagris gallopavo is animal",user_id:6},
{title:"Ringtail",description:"Bassariscus astutus is animal",user_id:3},
{title:"Creeper, black-tailed tree",description:"Climacteris melanura is animal",user_id:8},
{title:"Heron, yellow-crowned night",description:"Nyctanassa violacea is animal",user_id:2},
{title:"North American beaver",description:"Castor canadensis is animal",user_id:1},
{title:"Native cat",description:"Dasyurus viverrinus is animal",user_id:1},
{title:"Boa, cook's tree",description:"Corallus hortulanus cooki is animal",user_id:3},
{title:"Bahama pintail",description:"Anas bahamensis is animal",user_id:5},
{title:"Dove, rock",description:"Columba livia is animal",user_id:1},
{title:"Ground monitor (unidentified)",description:"Varanus sp. is animal",user_id:1},
{title:"Oryx, fringe-eared",description:"Oryx gazella callotis is animal",user_id:8},
{title:"Cormorant, flightless",description:"Nannopterum harrisi is animal",user_id:3},
{title:"Dragon, ornate rock",description:"Ctenophorus ornatus is animal",user_id:5},
{title:"Mountain duck",description:"Hymenolaimus malacorhynchus is animal",user_id:1},
{title:"Heron, yellow-crowned night",description:"Nyctanassa violacea is animal",user_id:6},
{title:"Black-footed ferret",description:"Mustela nigripes is animal",user_id:2},
{title:"Brazilian otter",description:"Pteronura brasiliensis is animal",user_id:6},
{title:"Puna ibis",description:"Plegadis ridgwayi is animal",user_id:4},
{title:"White-tailed deer",description:"Odocoilenaus virginianus is animal",user_id:7},
{title:"Vulture, turkey",description:"Cathartes aura is animal",user_id:1},
{title:"Antelope ground squirrel",description:"Ammospermophilus nelsoni is animal",user_id:4},
{title:"Wallaby, whip-tailed",description:"Macropus parryi is animal",user_id:1},
{title:"Zorro, common",description:"Dusicyon thous is animal",user_id:6},
{title:"Indian red admiral",description:"Vanessa indica is animal",user_id:6},
{title:"Turtle, long-necked",description:"Chelodina longicollis is animal",user_id:5},
{title:"Stork, white-necked",description:"Ciconia episcopus is animal",user_id:7},
{title:"Curve-billed thrasher",description:"Toxostoma curvirostre is animal",user_id:6},
{title:"Tortoise, burmese black mountain",description:"Manouria emys is animal",user_id:8},
{title:"Brown antechinus",description:"Antechinus flavipes is animal",user_id:5},
{title:"Bear, american black",description:"Ursus americanus is animal",user_id:6},
{title:"Crowned hawk-eagle",description:"Spizaetus coronatus is animal",user_id:2},
{title:"Bat, little brown",description:"Myotis lucifugus is animal",user_id:9},
{title:"Monkey, bleeding heart",description:"Theropithecus gelada is animal",user_id:9},
{title:"Knob-nosed goose",description:"Sarkidornis melanotos is animal",user_id:3},
{title:"Guanaco",description:"Lama guanicoe is animal",user_id:6},
{title:"Baboon, chacma",description:"Papio ursinus is animal",user_id:6},
{title:"Emerald green tree boa",description:"Boa caninus is animal",user_id:4},
{title:"Vulture, lappet-faced",description:"Aegypius tracheliotus is animal",user_id:6},
{title:"Striped hyena",description:"Hyaena hyaena is animal",user_id:3},
{title:"Three-banded plover",description:"Charadrius tricollaris is animal",user_id:6},
{title:"Dove, rock",description:"Columba livia is animal",user_id:7},
{title:"Flicker, field",description:"Colaptes campestroides is animal",user_id:7},
{title:"Tortoise, desert",description:"Gopherus agassizii is animal",user_id:4},
{title:"Eagle, white-bellied sea",description:"Haliaetus leucogaster is animal",user_id:5},
{title:"Red sheep",description:"Ovis ammon is animal",user_id:1},
{title:"Screamer, crested",description:"Chauna torquata is animal",user_id:8},
{title:"Zorro, azara's",description:"Pseudalopex gymnocercus is animal",user_id:8},
{title:"Boa, cook's tree",description:"Corallus hortulanus cooki is animal",user_id:7},
{title:"Blue-faced booby",description:"Sula dactylatra is animal",user_id:3},
{title:"Yellow-rumped siskin",description:"Carduelis uropygialis is animal",user_id:1},
{title:"Elegant crested tinamou",description:"Eudromia elegans is animal",user_id:7},
{title:"Dog, black-tailed prairie",description:"Cynomys ludovicianus is animal",user_id:8},
{title:"Caribou",description:"Rangifer tarandus is animal",user_id:6},
{title:"Silver-backed fox",description:"Vulpes chama is animal",user_id:1},
{title:"Red-tailed wambenger",description:"Phascogale calura is animal",user_id:1},
{title:"Macaw, blue and yellow",description:"Ara ararauna is animal",user_id:8},
{title:"Snake, buttermilk",description:"Coluber constrictor is animal",user_id:4},
{title:"Heron, goliath",description:"Ardea golieth is animal",user_id:2},
{title:"Collared peccary",description:"Tayassu tajacu is animal",user_id:4},
{title:"Oryx, beisa",description:"Oryx gazella is animal",user_id:8},
{title:"Margay",description:"Felis wiedi or Leopardus weidi is animal",user_id:7},
{title:"Rat, white-faced tree",description:"Echimys chrysurus is animal",user_id:7},
{title:"Blue wildebeest",description:"Connochaetus taurinus is animal",user_id:3},
{title:"Deer, red",description:"Cervus elaphus is animal",user_id:9},
{title:"African elephant",description:"Loxodonta africana is animal",user_id:5},
{title:"Buffalo, american",description:"Bison bison is animal",user_id:5},
{title:"Lesser masked weaver",description:"Ploceus intermedius is animal",user_id:7},
{title:"Indian peacock",description:"Pavo cristatus is animal",user_id:1},
{title:"Phascogale, brush-tailed",description:"Phascogale tapoatafa is animal",user_id:5},
{title:"Common goldeneye",description:"Bucephala clangula is animal",user_id:7},
{title:"Three-banded plover",description:"Charadrius tricollaris is animal",user_id:2},
{title:"Ass, asiatic wild",description:"Equus hemionus is animal",user_id:2},
{title:"Parakeet, rose-ringed",description:"Psittacula krameri is animal",user_id:5},
{title:"Goldeneye, barrows",description:"Bucephala clangula is animal",user_id:3},
{title:"Phalarope, red-necked",description:"Phalaropus lobatus is animal",user_id:1},
{title:"Bee-eater, white-fronted",description:"Merops bullockoides is animal",user_id:1},
{title:"Racer snake",description:"Coluber constrictor is animal",user_id:1},
{title:"Common zebra",description:"Equus burchelli is animal",user_id:1},
{title:"Squirrel, pine",description:"Tamiasciurus hudsonicus is animal",user_id:4},
{title:"Nubian bee-eater",description:"Merops nubicus is animal",user_id:6},
{title:"Stilt, black-winged",description:"Himantopus himantopus is animal",user_id:2},
{title:"Ibis, sacred",description:"Threskionis aethiopicus is animal",user_id:4},
{title:"Lesser double-collared sunbird",description:"Nectarinia chalybea is animal",user_id:2},
{title:"Violet-crested turaco",description:"Tauraco porphyrelophus is animal",user_id:4},
{title:"Indian giant squirrel",description:"Ratufa indica is animal",user_id:2},
{title:"Sugar glider",description:"Petaurus breviceps is animal",user_id:1},
{title:"Snake, green vine",description:"Oxybelis fulgidus is animal",user_id:8},
{title:"Bohor reedbuck",description:"Redunca redunca is animal",user_id:1},
{title:"Cockatoo, red-tailed",description:"Calyptorhynchus magnificus is animal",user_id:8},
{title:"Heron, gray",description:"Ardea cinerea is animal",user_id:7},
{title:"Stork, black-necked",description:"Ephippiorhynchus mycteria is animal",user_id:1},
{title:"Cockatoo, long-billed",description:"Cacatua tenuirostris is animal",user_id:9},
{title:"Glider, squirrel",description:"Petaurus norfolcensis is animal",user_id:4},
{title:"Nubian bee-eater",description:"Merops nubicus is animal",user_id:2},
{title:"Weaver, white-browed sparrow",description:"Plocepasser mahali is animal",user_id:1},
{title:"Gull, kelp",description:"Larus dominicanus is animal",user_id:8},
{title:"Cougar",description:"Felis concolor is animal",user_id:8},
{title:"Giant anteater",description:"Myrmecophaga tridactyla is animal",user_id:1},
{title:"Pintail, bahama",description:"Anas bahamensis is animal",user_id:3},
{title:"Sparrow, house",description:"Passer domesticus is animal",user_id:8},
{title:"Snowy egret",description:"Egretta thula is animal",user_id:3},
{title:"Otter, brazilian",description:"Pteronura brasiliensis is animal",user_id:7},
{title:"Long-billed corella",description:"Cacatua tenuirostris is animal",user_id:8},
{title:"Wildebeest, blue",description:"Connochaetus taurinus is animal",user_id:1},
{title:"Monkey, bleeding heart",description:"Theropithecus gelada is animal",user_id:5},
{title:"Mynah, indian",description:"Acridotheres tristis is animal",user_id:9},
{title:"Dragon, western bearded",description:"Amphibolurus barbatus is animal",user_id:7},
{title:"Cormorant, great",description:"Phalacrocorax carbo is animal",user_id:1},
{title:"Dragon, frilled",description:"Chlamydosaurus kingii is animal",user_id:2},
{title:"Australian brush turkey",description:"Alectura lathami is animal",user_id:3},
{title:"Arctic tern",description:"Sterna paradisaea is animal",user_id:5},
{title:"Weaver, chestnut",description:"Ploceus rubiginosus is animal",user_id:4},
{title:"Feral rock pigeon",description:"Columba livia is animal",user_id:8},
{title:"Bee-eater, nubian",description:"Merops nubicus is animal",user_id:6},
{title:"Ring-tailed gecko",description:"Cyrtodactylus louisiadensis is animal",user_id:6},
{title:"Eagle, african fish",description:"Haliaetus vocifer is animal",user_id:1},
{title:"Gray langur",description:"Semnopithecus entellus is animal",user_id:6},
{title:"Racer, american",description:"Coluber constrictor is animal",user_id:3},
{title:"Guanaco",description:"Lama guanicoe is animal",user_id:7},
{title:"Western pygmy possum",description:"Cercatetus concinnus is animal",user_id:8},
{title:"African polecat",description:"Ictonyx striatus is animal",user_id:7},
{title:"Rabbit, eastern cottontail",description:"Sylvilagus floridanus is animal",user_id:6},
{title:"Porcupine, north american",description:"Erethizon dorsatum is animal",user_id:3},
{title:"Pelican, australian",description:"Pelecanus conspicillatus is animal",user_id:9},
{title:"Dingo",description:"Canis dingo is animal",user_id:1},
{title:"Gazelle, thomson's",description:"Gazella thompsonii is animal",user_id:9},
{title:"Lesser masked weaver",description:"Ploceus intermedius is animal",user_id:4},
{title:"Hartebeest, coke's",description:"Alcelaphus buselaphus cokii is animal",user_id:4},
{title:"Boar, wild",description:"Sus scrofa is animal",user_id:3},
{title:"Squirrel, palm",description:"Funambulus pennati is animal",user_id:9},
{title:"Kangaroo, brush-tailed rat",description:"Bettongia penicillata is animal",user_id:1},
{title:"Possum, pygmy",description:"Acrobates pygmaeus is animal",user_id:6},
{title:"Pied avocet",description:"Recurvirostra avosetta is animal",user_id:8},
{title:"Dusky gull",description:"Larus fuliginosus is animal",user_id:7},
{title:"Paca",description:"Agouti paca is animal",user_id:3},
{title:"Heron, yellow-crowned night",description:"Nyctanassa violacea is animal",user_id:1},
{title:"Aardwolf",description:"Proteles cristatus is animal",user_id:8},
{title:"Cow, scottish highland",description:"Bos taurus is animal",user_id:1},
{title:"Gila monster",description:"Heloderma horridum is animal",user_id:6},
{title:"Lappet-faced vulture",description:"Aegypius tracheliotus is animal",user_id:6},
{title:"Pelican, australian",description:"Pelecanus conspicillatus is animal",user_id:3},
{title:"Zorilla",description:"Ictonyx striatus is animal",user_id:4},
{title:"Waxbill, violet-eared",description:"Uraeginthus granatina is animal",user_id:8},
{title:"Stork, saddle-billed",description:"Ephipplorhynchus senegalensis is animal",user_id:7},
{title:"African lynx",description:"Felis caracal is animal",user_id:8},
{title:"African bush squirrel",description:"Paraxerus cepapi is animal",user_id:4},
{title:"Grison",description:"Galictis vittata is animal",user_id:5},
{title:"Red phalarope",description:"Phalaropus fulicarius is animal",user_id:9},
{title:"Puma, south american",description:"Felis concolor is animal",user_id:1},
{title:"Red kangaroo",description:"Macropus rufus is animal",user_id:1},
{title:"Cattle egret",description:"Bubulcus ibis is animal",user_id:1},
{title:"Short-nosed bandicoot",description:"Isoodon obesulus is animal",user_id:4},
{title:"African clawless otter",description:"Aonyx capensis is animal",user_id:7},
{title:"Honey badger",description:"Mellivora capensis is animal",user_id:5},
{title:"Black-cheeked waxbill",description:"Estrilda erythronotos is animal",user_id:2},
{title:"Greater sage grouse",description:"Centrocercus urophasianus is animal",user_id:6},
{title:"Boar, wild",description:"Sus scrofa is animal",user_id:2},
{title:"Red howler monkey",description:"Alouatta seniculus is animal",user_id:1},
{title:"Squirrel, nelson ground",description:"Ammospermophilus nelsoni is animal",user_id:8},
{title:"Malabar squirrel",description:"Ratufa indica is animal",user_id:3},
{title:"Nuthatch, red-breasted",description:"Sitta canadensis is animal",user_id:5},
{title:"Dog, raccoon",description:"Nyctereutes procyonoides is animal",user_id:6},
{title:"Bennett's wallaby",description:"Macropus rufogriseus is animal",user_id:6},
{title:"Puku",description:"Kobus vardonii vardoni is animal",user_id:2},
{title:"Gerenuk",description:"Litrocranius walleri is animal",user_id:4},
{title:"Phascogale, red-tailed",description:"Phascogale calura is animal",user_id:2},
{title:"Fox, blue",description:"Alopex lagopus is animal",user_id:2},
{title:"Serval",description:"Felis serval is animal",user_id:4},
{title:"Pied avocet",description:"Recurvirostra avosetta is animal",user_id:1},
{title:"Rainbow lory",description:"Trichoglossus haematodus moluccanus is animal",user_id:5},
{title:"Brush-tailed bettong",description:"Bettongia penicillata is animal",user_id:7},
{title:"Brocket, brown",description:"Mazama gouazoubira is animal",user_id:5},
{title:"Southern ground hornbill",description:"Bucorvus leadbeateri is animal",user_id:4},
{title:"Lory, rainbow",description:"Trichoglossus haematodus moluccanus is animal",user_id:1},
{title:"Vulture, griffon",description:"Gyps fulvus is animal",user_id:1},
{title:"Langur, common",description:"Semnopithecus entellus is animal",user_id:5},
{title:"White-fronted bee-eater",description:"Merops bullockoides is animal",user_id:1},
{title:"Parrot, hawk-headed",description:"Deroptyus accipitrinus is animal",user_id:3},
{title:"Hornbill, leadbeateri's ground",description:"Bucorvus leadbeateri is animal",user_id:4},
{title:"Platypus",description:"Ornithorhynchus anatinus is animal",user_id:7},
{title:"Lion, steller's sea",description:"Eumetopias jubatus is animal",user_id:9},
{title:"Dabchick",description:"Tachybaptus ruficollis is animal",user_id:3},
{title:"White-winged tern",description:"Chlidonias leucopterus is animal",user_id:4},
{title:"Long-tailed jaeger",description:"Stercorarius longicausus is animal",user_id:4},
{title:"Tailless tenrec",description:"Tenrec ecaudatus is animal",user_id:9},
{title:"Phalarope, red",description:"Phalaropus fulicarius is animal",user_id:8},
{title:"Francolin, swainson's",description:"Francolinus swainsonii is animal",user_id:1},
{title:"Wallaby, tammar",description:"Macropus eugenii is animal",user_id:4},
{title:"Shrew, mandras tree",description:"Anathana ellioti is animal",user_id:5},
{title:"Crane, stanley",description:"Anthropoides paradisea is animal",user_id:3},
{title:"Colobus, black and white",description:"Colobus guerza is animal",user_id:3},
{title:"Honey badger",description:"Mellivora capensis is animal",user_id:2}])


